### PR TITLE
misc fixes/improvements

### PR DESCRIPTION
**Pull request by cbalster**

### CODE REVIEW

**Comment by stephanlindauer** [comment]
nice. thx!
did you find these problems by linting the project?

**Comment by cbalster** [comment]
For the first commit yes, most of them. The second one I noticed when looking at the sternfahrt route feature. I'll push some more changes tonight regarding that :)

**Comment by stephanlindauer** [comment]
ok. keep in mind though that that whole thing is a work in progress. if you switch it on you will see that the routes will get drawn on top of each other again and again every time we trigger a redraw.

**Comment by cbalster** [comment]
Yeah, I noticed that. Also the checkbox state in the overflow menu is behaving incorrectly since you have the menu handling code in the SuperFragment. Therefore each fragment has it's own callbacks and state variable.

**Comment by stephanlindauer** [comment]
true. i cant remember why i didn't attach that to the activity. there was a reason. 
disclaimer: reason might have been that i was and probably still am a bit of an android n00b ;)

**Comment by cbalster** [comment]
:D 
I moved all that stuff into Main and removed the SuperFragment - so far no problems. If you remember why you did it let me know so I don't break stuff ;)

**Pull request merged**
